Algoritmo "Soma"


Var

      quantidade, preco, recebido, troco: inteiro



Inicio

           escreva(" Preço unitário do produto: ")
           leia (preco)
           escreva(" Quantidade comprada: ")
           leia (quantidade)
           escreva(" Dinheiro recebido: ")
           leia (recebido)



            troco <-  recebido - ( preco * quantidade )
            escreva (" Troco = " , troco )

Fimalgoritmo